import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';
const supabase = createClient(supabaseUrl, supabaseKey);

export async function POST(req: Request) {
  try {
    const body = await req.json();

    // 1. Slack URL Verification Handshake
    if (body.type === 'url_verification') {
      return NextResponse.json({ challenge: body.challenge });
    }

    // 2. Process incoming app mention events
    if (body.event && body.event.type === 'app_mention') {
      // Ignore messages generated by bots to prevent infinite response loops
      if (body.event.bot_id || body.event.subtype === 'bot_message') {
        return NextResponse.json({ status: 'ok' });
      }

      const teamId = body.team_id;
      const channel = body.event.channel;
      let rawText = body.event.text || '';

      // Clean the prompt by removing the <@BOT_ID> tag
      const userPrompt = rawText.replace(/<@[^>]+>/g, '').trim() || 'Hello';

      // Lookup customer's token from Supabase
      const { data: config, error } = await supabase
        .from('integrations')
        .select('slack_token')
        .eq('team_id', teamId)
        .single();

      if (error || !config?.slack_token) {
        console.error(`No Slack token registered for workspace ${teamId}`);
        return NextResponse.json({ status: 'ok' });
      }

      const botToken = config.slack_token;

      // Generate AI answer with Groq
      let aiResponse = "Hello! I am your AutoCloud AI assistant. How can I help you today?";
      const groqApiKey = process.env.GROQ_API_KEY;

      if (groqApiKey) {
        try {
          const groqRes = await fetch('https://api.groq.com/openai/v1/chat/completions', {
            method: 'POST',
            headers: {
              Authorization: `Bearer ${groqApiKey}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              model: 'llama-3.3-70b-versatile',
              messages: [
                {
                  role: 'system',
                  content: 'You are an intelligent, concise AI workplace assistant.',
                },
                { role: 'user', content: userPrompt },
              ],
            }),
          });

          if (groqRes.ok) {
            const data = await groqRes.json();
            aiResponse = data.choices?.[0]?.message?.content || aiResponse;
          }
        } catch (groqErr) {
          console.error('Groq API failure:', groqErr);
        }
      }

      // Send response back to customer's Slack channel
      await fetch('https://slack.com/api/chat.postMessage', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${botToken}`,
          'Content-Type': 'application/json; charset=utf-8',
        },
        body: JSON.stringify({
          channel: channel,
          text: aiResponse,
        }),
      });
    }

    return NextResponse.json({ status: 'ok' });
  } catch (err) {
    console.error('Slack Webhook Route Error:', err);
    return NextResponse.json({ status: 'ok' });
  }
}